### ISSUE TITLE
Trouble following the quickstart guide

### ISSUE THREAD

**Issue by wongjoel** [Fastcode/VisualMesh#2]
I've been following the quickstart guide, and have reached the point where you train the network. This fails inside tensorflow with the following error `Feature: lens/k (data type: float) is required but could not be found.`

I'm running off the master branch using Docker on Ubuntu on WSL2. My dataset is the sample data on the quickstart page repeated 100 times.

I'm not quite sure what it means that a Tensorflow feature is missing. Is this an error with my environment/dataset, or an issue with the codebase?

Thanks.

Full stacktrace below:
```bash
joel@DESKTOP-RALSHQE:~/code/VisualMesh$ docker run -u $(id -u):$(id -g) -it --rm --volume $(pwd):/workspace visualmesh:latest ./mesh.py train output
2020-12-12 04:25:27.758331: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: UNKNOWN ERROR (-1)
2020-12-12 04:25:33.359456: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.359499: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.359555: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.359935: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.360140: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.360253: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.360298: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.361080: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.361137: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
2020-12-12 04:25:33.361512: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2102, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 758, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2610, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: lens/k (data type: float) is required but could not be found.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mesh.py", line 86, in <module>
    training.train(config, network_path)
  File "/workspace/training/training.py", line 100, in train
    ImageCallback(config, output_path),
  File "/workspace/training/flavour/image_callback.py", line 34, in ImageCallback
    colours=[c["colours"][0] for c in classes],
  File "/workspace/training/callbacks/classification_images.py", line 39, in __init__
    for d in dataset.take(1):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Feature: lens/k (data type: float) is required but could not be found.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
joel@DESKTOP-RALSHQE:~/code/VisualMesh$
```

**Comment by wongjoel** [comment]
Okay, so after discussions, the error message
```
0-12-12 04:25:33.359456: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at example_parsing_ops.cc:94 : Invalid argument: Feature: lens/k (data type: float) is required but could not be found.
```
comes from the tfrecord not containing the feature "lens/k".

This occurred because the script `./training/build_dataset.py <path/to/images> <path/to/output>` which is supposed to make a dataset does not add the feature.

The long term solution is to fix the `./training/build_dataset.py` script, but in the short term, this can be fixed by adding the field to the tfrecord.

**Comment by TrentHouliston** [comment]
Fixed in https://github.com/Fastcode/VisualMesh/commit/b35f1a8627132cc01bab67b7b9fb07f7f33f0ab2
